name: Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set image tag
        id: image_tag
        shell: pwsh
        run: |
          $timestamp = Get-Date -UFormat "%s"
          Write-Output "tag=my-image-name:$timestamp" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Build the Docker image
        shell: pwsh
        run: docker build . --file Dockerfile --tag ${{ steps.image_tag.outputs.tag }}
